server:
  port: 9900

spring:
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
        max-wait: -1ms


  kafka:
    template:
      default-topic: simple-message-topic
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: simple-kotlin-consumer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092

  output:
    ansi:
      enabled: ALWAYS

#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.password=
#
#spring.redis.lettuce.pool.max-active=7
#spring.redis.lettuce.pool.max-idle=7
#spring.redis.lettuce.pool.min-idle=2
#spring.redis.lettuce.pool.max-wait=-1ms
#spring.redis.lettuce.shutdown-timeout=200ms

##JPA Settings
##JPA Configuration
#spring.jpa.show-sql=false
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.database-platform=org.hibernate.dialect.MySQL57InnoDBDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#
##Data Source Settings Mariadb
#spring.datasource.url=jdbc:mariadb://localhost/kotlin
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.dbcp2.test-while-idle=true
#spring.datasource.dbcp2.validation-query=SELECT 1
#spring.datasource.continue-on-error=false
#
##Data Source Settings Postgresql
#spring.datasource.url=jdbc:postgresql://localhost/testdb
#spring.datasource.username=postgres
#spring.datasource.password=123
#
##Data Source Settings Mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=root
#spring.datasource.password=12345
#
##Data Source Settings H2DB
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:tcp://localhost/~/mydb
#spring.datasource.username=sa
#spring.datasource.password=cp
#
#  # Pretty-print JSON responses
#spring.jackson.serialization.indent_output=true
#
##Add Initial Date for Testing
#spring.datasource.initialize=true
#spring.datasource.data=classpath:data.sql

##Connection Pool Configuration
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=12
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.max-lifetime=1200000
